ARG SHA=latest
FROM openttd/dorpsgek-runner:${SHA}

ENV KUBECTL_VERSION="v1.11.1"

RUN apt-get update && apt-get install -y --no-install-recommends \
		curl \
    && curl -L https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl \
    && chmod +x /usr/local/bin/kubectl \
    && apt-get remove -y curl \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*
